### ISSUE TITLE
推理报错

### ISSUE THREAD

**Issue by 4nthon** [littletomatodonkey/insight-face-paddle#22]
`-------------------------------------------------------------------------------------

                                      PaddleFace                                     

+----------------+------------------------------------------------------------------+

|     Param      |                              Value                               |

+----------------+------------------------------------------------------------------+

|   det_model    |                            BlazeFace                             |

|   rec_model    |                            MobileFace                            |

|    use_gpu     |                               True                               |

| enable_mkldnn  |                              False                               |

|  cpu_threads   |                                1                                 |

|     input      |                               None                               |

|     output     |           /home/nvidia/insight-face-paddle-main/output           |

|      det       |                               True                               |

|   det_thresh   |                               0.8                                |

|      rec       |                               True                               |

|     index      | /home/nvidia/insight-face-paddle-main/demo/predixr_img/index.bin |

|    cdd_num     |                                5                                 |

|   rec_thresh   |                               0.45                               |

| max_batch_size |                                1                                 |

|  build_index   |                               None                               |

|    img_dir     |                               None                               |

|     label      |                               None                               |

+----------------+------------------------------------------------------------------+

                               Powered by PaddlePaddle!                              

-------------------------------------------------------------------------------------

WARNING:root:The directory of input contine directory or not supported file type, only support: {'jpg', 'tif', 'bmp', 'jpeg', 'rgb', 'png', 'tiff'}

Traceback (most recent call last):

  File "pre.py", line 16, in <module>

    print(next(res))

  File "/home/nvidia/insight-face-paddle-main/insightface_paddle.py", line 759, in predict

    labels = self.rec_predictor.retrieval(np_feature)

  File "/home/nvidia/insight-face-paddle-main/insightface_paddle.py", line 558, in retrieval

    -self.cdd_num)[-self.cdd_num:]

  File "<__array_function__ internals>", line 6, in argpartition

  File "/home/nvidia/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 832, in argpartition

    return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)

  File "/home/nvidia/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc

    return bound(*args, **kwds)

ValueError: kth(=-2) out of bounds (3)

`
demo测试没有问题，换成自己的数据之后似乎建立索引以后那个索引会报错，请问这个问题如何解决？
另外，请问建立索引的最少图片张数（每个人）是多少？

**Comment by 4nthon** [comment]
`import insightface_paddle as face

import logging

logging.basicConfig(level=logging.INFO)



parser = face.parser()

args = parser.parse_args()



args.det = True

args.rec = True

args.index = "/home/nvidia/insight-face-paddle-main/demo/predixr_img/index.bin"

args.output = "/home/nvidia/insight-face-paddle-main/output"

input_path = "/home/nvidia/insight-face-paddle-main/demo/predixr_img/"



predictor = face.InsightFace(args)

res = predictor.predict(input_path, print_info=True)

print(next(res))



`
测试代码如上
